/* generated by info.scce.dime.generator.scheme.ModelGenerator */
package de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app;
@de.ls5.dywa.annotations.IdRef(id = 3L)
@de.ls5.dywa.annotations.OriginalName(name = "Tile")
@de.ls5.dywa.annotations.ShortDescription(description = "")
@de.ls5.dywa.annotations.LongDescription(description = "")
public interface Tile extends de.ls5.dywa.generated.util.Identifiable {
	@de.ls5.dywa.annotations.IdRef(id = 13L)
	@de.ls5.dywa.annotations.OriginalName(name = "x")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	java.lang.Long getx();
	
	@de.ls5.dywa.annotations.IdRef(id = 13L)
	@de.ls5.dywa.annotations.OriginalName(name = "x")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	void setx(java.lang.Long object);
	
	@de.ls5.dywa.annotations.IdRef(id = 14L)
	@de.ls5.dywa.annotations.OriginalName(name = "y")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	java.lang.Long gety();
	
	@de.ls5.dywa.annotations.IdRef(id = 14L)
	@de.ls5.dywa.annotations.OriginalName(name = "y")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	void sety(java.lang.Long object);
	
	@de.ls5.dywa.annotations.IdRef(id = 15L)
	@de.ls5.dywa.annotations.OriginalName(name = "colour")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	java.lang.Long getcolour();
	
	@de.ls5.dywa.annotations.IdRef(id = 15L)
	@de.ls5.dywa.annotations.OriginalName(name = "colour")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	void setcolour(java.lang.Long object);
	
	@de.ls5.dywa.annotations.IdRef(id = 16L)
	@de.ls5.dywa.annotations.OriginalName(name = "population")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	java.lang.Long getpopulation();
	
	@de.ls5.dywa.annotations.IdRef(id = 16L)
	@de.ls5.dywa.annotations.OriginalName(name = "population")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	void setpopulation(java.lang.Long object);
	
	@de.ls5.dywa.annotations.IdRef(id = 17L)
	@de.ls5.dywa.annotations.OriginalName(name = "capacity")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	java.lang.Long getcapacity();
	
	@de.ls5.dywa.annotations.IdRef(id = 17L)
	@de.ls5.dywa.annotations.OriginalName(name = "capacity")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	void setcapacity(java.lang.Long object);
	
	@de.ls5.dywa.annotations.IdRef(id = 18L)
	@de.ls5.dywa.annotations.OriginalName(name = "board")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Board getboard();
	
	@de.ls5.dywa.annotations.IdRef(id = 18L)
	@de.ls5.dywa.annotations.OriginalName(name = "board")
	@de.ls5.dywa.annotations.ShortDescription(description = "")
	@de.ls5.dywa.annotations.LongDescription(description = "")
	void setboard(de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Board object);
	

	// EXTENSION ATTRIBUTES

	// CUSTOM LIST IMPL
	static class CustomListImpl<T extends de.ls5.dywa.generated.util.Identifiable> extends java.util.AbstractList<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> {
	
		private final java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> delegate;
		private final BiDirectionalHelper<T> bidirectionalHelper;
		private boolean bidirectionalDirtyFlag;
	
		public CustomListImpl(final java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> delegate) {
			this(delegate, null);
		}
	
		public CustomListImpl(final java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> delegate, final BiDirectionalHelper<T> bidirectionalHelper) {
			this.delegate = delegate;
			this.bidirectionalHelper = bidirectionalHelper;
		}
	
		@java.lang.Override
		public int size() {
			return this.delegate.size();
		}
	
		@java.lang.Override
		public de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile get(int index) {
				return this.delegate.get(index);
		}
	
		@java.lang.Override
		public de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile set(int index, de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile element) {
	
			final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile replaced = this.delegate.set(index, element);
	
			if (element.equals(replaced)) {
				return element;
			}
	
			if (this.bidirectionalHelper != null) {
				this.bidirectionalHelper.clearReference(element);
				this.bidirectionalHelper.setReference(replaced);
			}
	
			return replaced;
		}
	
		@java.lang.Override
		public void add(int index, de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile element) {
	
			if (!this.bidirectionalDirtyFlag) {
	
				this.bidirectionalDirtyFlag = true;
	
				this.delegate.add(index, element);
	
				if (this.bidirectionalHelper != null) {
					bidirectionalHelper.setReference(element);
				}
	
				this.bidirectionalDirtyFlag = false;
			}
		}
	
		@java.lang.Override
		public de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile remove(int index) {
	
			if (!this.bidirectionalDirtyFlag) {
	
				this.bidirectionalDirtyFlag = true;
				final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile result = this.delegate.remove(index);
	
				if (this.bidirectionalHelper != null) {
					this.bidirectionalHelper.clearReference(result);
				}
	
				this.bidirectionalDirtyFlag = false;
				return result;
			}
	
			return null;
		}
	}
	
	static class BiDirectionalHelper<T extends de.ls5.dywa.generated.util.Identifiable> {
	
		final java.util.function.BiConsumer<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile, T> setter;
		final java.util.function.Function<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile, java.util.List<T>> getter;
		final T owner;
	
		public BiDirectionalHelper(
				java.util.function.BiConsumer<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile, T> setter,
				T owner) {
	
			this.setter = setter;
			this.getter = null;
			this.owner = owner;
		}
	
		public BiDirectionalHelper(
				java.util.function.Function<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile, java.util.List<T>> getter,
				T owner) {
	
			this.setter = null;
			this.getter = getter;
			this.owner = owner;
		}
	
		public void setReference(final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile p) {
	
			// list mode
			if (this.getter != null) {
				getter.apply(p).add(owner);
			}
			// single mode
			else {
				setter.accept(p, owner);
			}
		}
	
		public void clearReference(final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile p) {
	
			// list mode
			if (this.getter != null) {
				getter.apply(p).remove(owner);
			}
			// single mode
			else {
				setter.accept(p, null);
			}
		}
	}

	default Tile casted(){
		return this;
	}
}
