/* generated by info.scce.dime.generator.scheme.ControllerGenerator */
package de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app;

import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile;

public interface TileController {

	Tile read(java.lang.Long id);

	java.util.List<Tile> findByProperties(Tile searchObject);

	Tile findFirstByProperties(Tile searchObject);

	java.util.Set<Tile> fetch();

	java.util.Set<Tile> fetchByName(java.lang.String name);

	Tile create(java.lang.String name);
	Tile createTransient(java.lang.String name);

	Tile createSearchObject(java.lang.String name);

	java.util.Set<Tile> fetchWithSubtypes();

	void delete(Tile entity);

	void deleteWithIncomingReferences(Tile entity);
}
