/* generated by info.scce.dime.generator.scheme.ModelGenerator */
package de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app;
@javax.persistence.Entity
@javax.persistence.Cacheable
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.READ_WRITE)
@javax.persistence.Table(name = "t_Board__pa7psw2see20bpb", indexes={@javax.persistence.Index(columnList="meta_inheritance")})
@de.ls5.dywa.annotations.IdRef(id = 2L)
public class BoardImpl implements Board {
	@javax.persistence.Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE)
	@javax.persistence.Column(name = "meta_id")
	private long id_;
	
	/* DYWA METADATA START */
	@javax.persistence.Column(name = "meta_name")
	private java.lang.String name_;
	
	@javax.persistence.Column(name = "meta_version")
	private long version_;
	
	@javax.persistence.Column(name = "meta_inheritance")
	private boolean inheritance_ = false;


	@javax.persistence.Transient
	private boolean bidirectionalDirtyFlag;
	/* DYWA METADATA END */

	
	/* MAIN ATTRIBUTES START */
	@de.ls5.dywa.annotations.IdRef(id = 12L)
	@org.hibernate.annotations.Cascade(org.hibernate.annotations.CascadeType.PERSIST)
	@javax.persistence.JoinTable(name="r_Board_Tile__voyfcg2tee20bpb", joinColumns = { @javax.persistence.JoinColumn(name = "r1_Board_id") }, inverseJoinColumns = { @javax.persistence.JoinColumn(name = "r2_Tile_id") })
	@org.hibernate.annotations.ManyToAny(metaColumn=@javax.persistence.Column(name="m_Tile_Type__voyfcg2tee20bpb"))
	@org.hibernate.annotations.AnyMetaDef(
		idType="long", metaType="string",
		metaValues={
			@org.hibernate.annotations.MetaValue(targetEntity=de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.TileImpl.class, value="_q_yjew2see20bpb")
		}
	)
	private java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> tile  = new java.util.ArrayList<>();
	
	/* MAIN ATTRIBUTES END */
	
	/* IMPLICIT ATTRIBUTES START */
	/* IMPLICIT ATTRIBUTES END */
	
	/* INHERITED MODELS START */
	/* INHERITED MODELS END */

	/* INHERITED ABSTRACT MODELS START */
	/* INHERITED ABSTRACT MODELS END */
	
	/* ADDITIONAL INHERITED MODELS START */
	/* ADDITIONAL INHERITED MODELS END */
	
	// Constructors
	public BoardImpl() {
	}



	// EXTENSION ATTRIBUTES

	public long getId_() {
		return this.id_;
	}

	public void setId_(final long id) {
		this.id_ = id;
	}

	@java.lang.Override
	public java.lang.String getDywaName() {
		return this.name_;
	}

	@java.lang.Override
	public void setDywaName(final java.lang.String name) {
		this.name_ = name;
	}

	// return existing id on runtime
	@java.lang.Override
	public long getDywaId() {
		return this.id_;
	}

	@java.lang.Override
	public long getDywaVersion() {
		return this.version_;
	}

	@java.lang.Override
	public void setDywaVersion(final long version) {
		this.version_ = version;
	}
	
	 @javax.persistence.Transient private java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> tileWrapper;
	@java.lang.Override
	public java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> gettile_Tile() {
		if(tileWrapper == null){
			tileWrapper = new de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile.CustomListImpl(this.tile,
			new de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile.BiDirectionalHelper<>(
				de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile::setboard
				,
				this.casted())
			);
		}
	
		return tileWrapper;
	}
	
	@java.lang.Override
	public void settile_Tile(java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> object) {
		if (!this.bidirectionalDirtyFlag) {
			this.bidirectionalDirtyFlag = true;
			final java.util.List<de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile> current = this.gettile_Tile();
				if(current != null){
					// redundant updates can be skipped
					if (object != null && current.equals(object)) {
						this.bidirectionalDirtyFlag = false;
					return;
				}
				current.clear();
				if(object != null){
					current.addAll(object);
				}
			}
			this.bidirectionalDirtyFlag = false;
		}
	}
	
	
	@java.lang.Override
	public String toString() {
		return "Board[id: " + this.id_ + ", name: " + this.name_ + "]";
	}
}

