/* generated by info.scce.dime.generator.scheme.ControllerGenerator */
package de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app;

import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Tile;
import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.TileImpl;
import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.TileSearch;

import java.util.Arrays;
import java.util.stream.Collectors;

@javax.enterprise.context.RequestScoped
public class TileControllerImpl implements TileController {
	private static final org.slf4j.Logger LOGGER =  org.slf4j.LoggerFactory.getLogger(TileController.class);

	@javax.persistence.PersistenceContext
	private javax.persistence.EntityManager entityManager;

	@javax.inject.Inject
	private de.ls5.dywa.generated.util.DomainFileController domainFileController;

@javax.inject.Inject //referenceMap
private de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app.BoardController boardController;

    
    @Override
	public Tile read(final java.lang.Long id) {

		 Tile result = entityManager.find(TileImpl.class, id);
		 	// delegate read until entity is found;
		return result;
	}

    @Override
	public java.util.List<Tile> findByProperties(Tile searchObject) {
		if (searchObject instanceof TileSearch) {
			TileSearch casted = (TileSearch) searchObject;

			java.util.List<Tile> list = buildSimpleQuery(casted.queryAttributes(), casted.queryListAttributes(), true).getResultList().stream().map(Tile::casted).collect(Collectors.toList());

			return list;
		} else {
			throw new java.lang.IllegalArgumentException("Search object required.");
		}
	}

	@Override
	public Tile findFirstByProperties(Tile searchObject) {
		if (searchObject instanceof TileSearch) {
			TileSearch casted = (TileSearch) searchObject;
			java.util.List<Tile> results = new java.util.ArrayList<Tile>();
			results.addAll(buildSimpleQuery(casted.queryAttributes(), casted.queryListAttributes(),false).setMaxResults(1).getResultList());
			return results.isEmpty() ? null : results.get(0);
		} else throw new java.lang.IllegalArgumentException("Search object required.");
	}

	@Override
	public java.util.Set<Tile> fetch() {
		return new java.util.HashSet<Tile>(buildSimpleQuery(null, null,false).getResultList());
	}

	@Override
	public java.util.Set<Tile> fetchByName(final java.lang.String name) {
		java.util.Map<String, Object> map = new java.util.HashMap<>();
		map.put("name_", name);
		java.util.HashSet<Tile> result = new java.util.HashSet<>(buildSimpleQuery(map, null,false).getResultList());
		return result;
	}

		@Override
		public Tile create(java.lang.String name) {
			TileImpl entity = new TileImpl();
			entity.setDywaName(name);
			entityManager.persist(entity);
			return entity;
		}

		@Override
		public Tile createTransient(java.lang.String name) {
			TileImpl entity = new TileImpl();
			entity.setDywaName(name);
			return entity;
		}

	@Override
	public Tile createSearchObject(java.lang.String name) {
		return new TileSearch(name);
	}

	@Override
	public java.util.Set<Tile> fetchWithSubtypes() {
		java.util.Set<Tile> list = buildSimpleQuery(null,null, true).getResultList().stream().map(Tile::casted).collect(Collectors.toSet());

		return list;
	}

	@Override
	public void delete(Tile entity) {

		if (entity instanceof TileImpl) {
			TileImpl impl = (TileImpl) entity;
			entityManager.remove(impl);
		}
		// delegate delete
	}
	
	@Override
	public void deleteWithIncomingReferences(Tile entityToDelete) {

		
		// Delete references from type Board
			de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Board searchBoard;
			searchBoard = new de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BoardSearch();	
				searchBoard.settile_Tile(java.util.Arrays.asList(entityToDelete));
			for (de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Board queryResult : this.boardController.findByProperties(searchBoard)) {
				queryResult.gettile_Tile().remove(entityToDelete);
			}
		delete(entityToDelete);
	}
	
	private javax.persistence.TypedQuery<TileImpl> buildSimpleQuery(java.util.Map<String, Object> attributeMap, java.util.Map<String, java.util.List> listAttributeMap, boolean withInherited) {
		java.lang.StringBuilder queryStr = new java.lang.StringBuilder("SELECT e FROM TileImpl e WHERE (true="+withInherited+" OR e.inheritance_ = false)");
		if (attributeMap != null) {
			for (java.util.Map.Entry<String, Object> entry : attributeMap.entrySet()) {
				queryStr.append(" AND e." + entry.getKey() + " = :" + entry.getKey().replaceAll("\\W", ""));
			}
		}
		if (listAttributeMap != null) {
			for (java.util.Map.Entry<String, java.util.List> entry : listAttributeMap.entrySet()) {
				if (entry.getValue() == null || entry.getValue().isEmpty()) {
					queryStr.append(" AND e." + entry.getKey() + " IS EMPTY");
				} else {
					String prefix = entry.getKey().replaceAll("\\W", "");
					for (int i = 0, s = entry.getValue().size(); i < s; i++) {
						queryStr.append(" AND :" + prefix + i + " MEMBER OF e." + entry.getKey());
					}
				}
			}
		}
		queryStr.append(" ORDER BY id_ DESC");
		javax.persistence.TypedQuery<TileImpl> query = entityManager.createQuery(queryStr.toString(), TileImpl.class);
		if (attributeMap != null) {
			for (java.util.Map.Entry<String, Object> entry : attributeMap.entrySet()) {
				query.setParameter(entry.getKey().replaceAll("\\W", ""), entry.getValue());
			}
		}
		if (listAttributeMap != null) {
			for (java.util.Map.Entry<String, java.util.List> entry : listAttributeMap.entrySet()) {
				if (entry.getValue() != null && !entry.getValue().isEmpty()) {
					String prefix = entry.getKey().replaceAll("\\W", "");
					for (int i = 0, s = entry.getValue().size(); i < s; i++) {
						query.setParameter(prefix + i, entry.getValue().get(i));
					}
				}
			}
		}
		query.setHint(org.hibernate.jpa.QueryHints.HINT_CACHEABLE,true);
		return query;
	}
}
