// generated by SelectiveGenerator#generate(ComplexTypeView view)
package de.ls5.dywa.generated.rest.types;

public class GameBoardBoardSelectivex1_Sw__HYPHEN_MINUS__VYWpvEe2h5bRrsXzQFA {

	public static void copy(
		final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.Board from,
		final de.ls5.dywa.generated.rest.types.Board to,
		final info.scce.dime.rest.ObjectCache objectCache) {
	
	
	
		if (objectCache.containsSelective(to, "GameBoardBoardSelectivex1_Sw__HYPHEN_MINUS__VYWpvEe2h5bRrsXzQFA")) {
			return;
		}
	
		to.setDywaId(from.getDywaId());
		to.setDywaVersion(from.getDywaVersion());
		to.setDywaName(from.getDywaName());
	
		// put to cache, after id has been set
		objectCache.putSelective(to, "GameBoardBoardSelectivex1_Sw__HYPHEN_MINUS__VYWpvEe2h5bRrsXzQFA");
	
	}
}
