// generated by info.scce.dime.generator.gui.rest.DartTOGeneratorHelper#generateGUIInputsDart

import 'dart:convert';
import 'package:app/src/models/Selectives.dart';
import 'package:app/src/models/FileReference.dart';
import 'package:app/src/core/dime_process_service.dart';
import 'package:app/src/data/Data.dart' as Data;
import 'package:app/src/models/FileReference.dart';

class GameBoard_Sw_45_VYWpvEe2h5bRrsXzQFAInput extends UserInteractionResponse {
	
	Data.Board board = null;
	
	GameBoard_Sw_45_VYWpvEe2h5bRrsXzQFAInput(Map<String,dynamic> map, Map<String,dynamic> cache)
	{
		 Map<String,dynamic> inputPorts = map['inputs'];
		if(inputPorts.containsKey('board')) {
			if(inputPorts['board']!=null){
				board = Data.Board.fromJSOG(jsog:inputPorts['board'],cache:cache);
			}
		}
	}
	
	@override
	bool startedByEvent() {
	    return false;
	}
	
	bool inpusChanged(GameBoard_Sw_45_VYWpvEe2h5bRrsXzQFAInput input) {
		return board != input.board;
	}
}
